---
title: "Paper_text_working_file"
author: "Addison"
date: "April 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

install.packages("tidyverse")

library(tidyverse)

#This was a paper completed for the course Water and Conflict. 

#Introduction
      With the recent military actions in Ukraine, the Saudi-Iranian proxy war in Yemen, and the ongoing civil war in Syria, it is easy to lose sight of arguably the most likely trigger area for a major interstate conflict today between great two powers. The continued dispute over the control of the South China Sea has resulted in several close encounters between military forces belonging to the United States and the Peoples Republic of China. In October of 2018 a Chinese destroyer passed within a few dozen feet of an American warship and on numerous occasions aircraft from both sides have intercepted one another in areal maneuvers with potentially global implications. With the increasing tensions in the South China Sea as well as the buildup of Chinese military forces in the region, the United States is challenged to meet to these actions or risk losing influence in a region with some of the most heavily used trade routes in the world. In order to do this the U.S. must deploy military assets thousands of miles from the nearest American shoreline and support those assets with steady stream of logistical and specialized support. This type of forward support can be accomplished through the use of overseas military installations. In terms of the South China Sea, American military bases in Korea, Guam, and Japan allow for the rapid deployment and sustainability of a large military force. China, for its part, has begun to build naval installations on the artificial islands it has constructed in the disputed zone. This would allow them to forward deploy their forces, as well as claim some level of legitimacy in their overall claim. 
     Naval bases placed abroad provide a state with the ability to project offensive force much further than if they were to only rely on military installations in their own territory. States with regional or even global hegemonic aspirations must build military outposts and naval installations if they have any hope projecting their power and influence beyond their own region. While there have been several studies that have looked into the effect of naval capacity on conflict initiation, there is very little research on the impact of fixed naval installations. In this paper I will try and fill that gap by examining the relationship between the proximity of a hegemon’s naval installations to initiating states of a maritime claim and the militarization of that dispute. In doing so this paper also examines several of the other prominent explanations for maritime claim militarization including relative capabilities of the disputants, regime typology, and specific issues about the claim (Hensel et al. 2008; Daniels & Mitchell 2017). The statistical analysis demonstrates that in fact proximity to a hegemon’s naval base does not have an effect on the militarization of a dispute. Further, this paper finds additional support for explanations based on issue salience for dispute militarization. 
     The remainder of the paper is divided into three sections, first will be a review of the relevant literature on military installations and their effects on conflict behavior. From this literature a theory will be developed linking naval installation proximity to conflict initiation. The second section will present the methods and data used in the statistical analysis. The third section will conclude the paper with a discussion about the implications of the findings and opportunities for future research.  
     
#Review of relevant literature
     More than seventy percent of the Earth’s surface is covered by water, so to be able to extend one’s influence and capabilities abroad, preeminence on the seas is a must-have. Today the issue of a maritime strategy has become even more important to the global strategy of a state. Globalization and technological advances along with vastly lower costs of sea transportation has resulted in an explosion in the importance and prevalence of international trade. Companies like Maersk shipping operate more than 550 cargo vessels and acquire as many as forty more every ear (Carmel 2008, 41). As a result, states must create a global maritime strategy which allows them to protect their interests abroad and ensure safe and productive commerce. For some states this means constructing their own blue water navy to allow them to project their power beyond the literal and coastal waters. Other states will attempt to form alliances with powerful naval states to gain access to their ports and the protection of their fleets. New types of threats as well as resurgent threats also impact the chosen strategy of a state. To address irregular threats, the U.S. has taken a combined approach in their maritime strategy by working with international partners as well as the private sector to reduce the threat of piracy and terrorism (Carmel 2008, 40-41).	
     The radical changes in the maritime threat environment has brought about new security demands such as cyber security, anti-piracy, and the increasing need to protect the ever-growing commercial shipping lanes which fuel the global economy. Changes in different authorities have also altered the way in which states conduct their maritime strategy. IGOs such as the UN and international laws such as the United Nations Convention on the Law of the Sea (UNCLOS), mean that naval theorists must think about different types of authority beyond that of their own government (Luke 2013, 11-12). The United States has largely adhered to a similar strategy for more than one hundred years. Sea power has played a significant role in U.S. global strategy, thanks in no small part to the father of American maritime strategy, Alfred Thayer Mahan (Baofu 2008, 63-64). However, new maritime strategy has changed the way the United States operates and addresses maritime concerns. While old doctrine focuses on the construction of large fleets of capital ships to dominate potential opponents, the new strategy places a greater emphasis on the prevention of wars in the first place. (Baofu 2008, 65-66).  
     The vast oceans have a unique stopping power, preventing some of the most powerful state from achieving their goals. (Mearsheimer 2001, 84). One way to overcome this stopping power is by establishing a military installation outside of the state’s borders. This would allow the hegemon to extend its naval reach and support its forces further than it would if it solely relied on deploying forces from its own soil. Seaports allow states to assemble and hold large military forces and to support those forces far from their homeport (Julien 1984, 103). States which have been traditionally seen as being hegemonic powers such as the United States, Great Britain, Spain, and the Netherlands each had enormous preponderance in naval capabilities. Great Britain for example in the late 1800s possessed roughly half of all shipping tonnage in the world, along with military ports in colonies worldwide. (Calder 2008, 7). The United States for its part currently maintain more aircraft carriers than any other state and has more blue water naval assets deployed at any given time than any other country. Even in the face of U.S. decline and rising regional powers, most states still look to the U.S. for protection of sea lanes and general maritime policing (Henry et al. 2012, 32). The U.S. is so important to international maritime security that if it were to reduce its role in ensuring that security, international commerce would be severely impacted (Lee 2017, 6). 
     States with powerful navies such as the United States and Great Britain in the past, will use their naval power to protect their interests. This includes preventing foreign powers from establishing what some refer to as “command of the sea” (Corbett 1984, 161-169). One of the seminal works on the importance of naval power comes from Alfred Mahan. Mahan (2004) argued that naval dominance was necessary for states to assume command of the seas, thereby ensuring the success of land operations, cutting off lines of communication and commerce to an enemy, and protecting one’s own commerce and interests. Naval forces positioned in strategic locations like Gibraltar or the Suez can allow states to set up blockades and chokepoints, denying an enemy access to the sea and cutting off commerce. (Crowl 1986, 452-455). 
     A military base positioned outside of one’s borders can offer a state multiple advantages. These bases allow the state to respond to threats without risking conflict within their own borders while also allowing for greater flexibility in strategic deterrence. They allow states to apply their capabilities at strategic strong points and to draw on the resources and assistance of their allies (Calder 2008, 7-33). Along with military benefits, these bass allow countries to ensure the safe flow of vital resources necessary for modern industry. American military bases in Africa for example allow for the United States to ensure the safe flow of goods and oil from the Middle East and Asia to the West. These resources were important enough to the United States that bases were constructed, and a task force dubbed the Rapid Deployment Force (RDF) was created to protect American oil interests (Mangi 1987, 100). Military bases in foreign lands also have a symbolic effect by demonstrating the resolve and capabilities of the state to both allies and rivals (Namkung & Lee 2012, 30)  
     Many U.S. bases overseas arose following the end of past wars and have remained open even in the absence of a clear military need. In fact, military bases are surprisingly resilient when the U.S. attempts to draw down its military presence or make fiscal cuts (Davis et all 2012, 29). The importance of naval bases as a way to project power has also been taken to heart by aspiring hegemons such as China. Through their “string of pearls” strategy, China has been establishing outposts and securing alliances in foreign countries as a means of spreading influence and extending their reach. These outposts serve to protect oil shipments to China as well as establish new shipping routes for Chinese goods (Crisher 2017, 2). The importance of naval bases cannot be understated. Not only do they provide the ability to project hard power beyond a state’s borders, but also their ability to influence the economy and politics of surrounding countries. To a hegemon seeking to maintain the status quo and prevent the rise of a potential challenger, their contribution is vital. 

Militarization of Maritime Claims
     The causes of maritime claim are often tied to disagreements over the management over some high valued resource. Fishing stocks, shipping routes, and non-renewable resources are often the causes that lead states to claim areas which are beyond their usual zone of control. While maritime claim rarely escalate to all wars, state shave threatened or even carried out lower levels of conflict. Militarized interstate disputes (MIDs) occur when states either threaten or carryout some form of military action short of war (Singer 1987). States will threaten or actively deploy military forces in response to perceived threats should their interests be at risk. 
     Several explanations have been presented for why maritime claims result in militarized disputes. One common explanation is economic opportunity or the availability of a high value resource. Oil and natural gas in particular have been found to increase the risk of a claim dispute escalating into militarized conflict (Nyman E2015, 1-7). Highly salient issues such as territorial claims, claims over areas with valuable resources, and areas considered to be in a strategic location have also been found to increase the risk of a militarized dispute (Hensel et al. 2008, 139).
     Another explanation for escalation, particularly in terms of territorial claims, is the change in relative capabilities of the actors involved. Bell (2017) finds that an increase in relative capabilities by a state which does not currently control the claimed territory dramatically increases the risk for armed conflict. However, research into maritime issues specifically has found that states with relatively equal capabilities are the most likely to see conflict. Disputes in which one state is overwhelmingly more powerful than the other are more likely to end in a peaceful settlement (Nemeth et al. 2014, 724; Hensel et al. 2008, 127).
     Proximity as a determinant in international conflict has been studied as it relates to escalation of conflicts among contiguous states as well as long distant conflicts. As Mearsheimer identified, oceans have a stopping power for states, preventing them from extending their influence and power (Mearsheimer 2001, 84). Kenneth Boulding (1962) argued that the power of a state is reduced as it tries to operate further from home. With each additional unit of distance, the ability of the state to influence others decreased. However, the impact of distance can be mitigated in certain circumstances. New technologies cut down on the amount of time that it takes to traverse vast distances, lessoning their impact (Starr 2005, 392). Navies allow for states to overcome the obstacle of oceans and distance and influence or engage noncontiguous states (Crisher 2017, 2). A naval base positioned closer to a hostile actor should allow for even more rapid, effective, and sustained intervention. These installations act as extensions of the state allowing them to deploy greater forces further and faster than if they were to only be based in the state’s territory (Julien 1984, 103). 

#Theory
The theoretical foundation for this paper lies with hegemonic stability theory. According to the theory, a single overwhelmingly dominant state is necessary for the creation and maintenance of an open and stable international structure. The hegemon will provide public goods in the form of order and security to the international system by providing benefits to those states which stay in line and punishing those states which seek to upset the status quo. The states which initiate the claims are by definition states which seek to upset the status quo by acquiring rights to certain area or by acquiring sovereignty over them outright. These revisionist states threaten the status quo and thus draw the attention of the hegemon. While the hegemon may not become militarily involved in every dispute or conflict that occurs, their overwhelming dominance and ability to do so, should they chose, will weigh on the decision making of the revisionist state. 
	Naval installations provide states with a base from which to launch offensive operations as well as supply forces already deployed. This can be particularly useful to a hegemon which is trying to maintain the status quo of the international system of which it sits as its de facto head. Militarized conflicts between smaller states may threaten to upset that status quo or give rise to a potential challenger, forcing the hegemon to respond by involving itself in the dispute and if needs be punish the belligerents. A hegemonic power is especially responsive to maritime issues as international trade and the ability to move forces across the oceans freely are of keen interest to a hegemonic power. Maritime claim which result in a military conflict are then likely to draw the hegemon into the dispute. This is evident by the fact that the United States has been involved in roughly a third of the MIDs resulting from disputed maritime claims in the Issue Correlates of War data.  
	As a result, knowing that the hegemon has an interest in preventing military conflict will affect the conflict behavior of other states in the system. This effect will be felt disproportionality by states which are closer to the United States than those which are further away. For example, Cuba is justifiably more sensitive to U.S. intervention than Madagascar since U.S. ships and aircraft launched from the United States can reach Cuba in a matter of hours, whereas a campaign to Madagascar could take days or weeks. This is where naval installations factor into the theory. A naval facility on the other side of the world can act as an extension of the United States, permitting it to deploy and support fleets and air wings as though they had been launched from its own soil. If a revisionist state believed that it would take time for the hegemon to respond, or that the distance across the seas would dissuade their involvement, then that revisionist state may be more inclined to try and coerce a more favorable settlement out of the other actor. However, having a hegemon’s naval installation in close proximity to that challenger will cause the same constraining effect as being in close proximity to the hegemon itself. As a result: 

H1) The likelihood of a militarized interstate dispute will increase as the distance between the challenger state and the nearest US naval installation increases. 

	The United States will likely not become militarily involved in every dispute or maritime claim that arises, though they will have a position preference based on their role as the hegemon. However, if that maritime claim were against a state with which the U.S. held an alliance, then the incentives for the U.S. to become involve would rise substantially. Threats or actions against members of the hegemon’s alliance structure may challenge the assumption that the U.S. can protect those states. Not becoming involved in claims or disputes which involve an ally may call into question the very credibility of the other alliances and their role as the hegemon. States will understand this when formulating their strategy for a claim, and will be less inclined to allow a claim against a U.S. ally escalate into a militarized dispute. And so:

H2) The likelihood of a maritime claim developing into a militarized dispute is reduced when the target of the claim holds an alliance with the hegemon.

#Research design
Testing these hypotheses presented unique data limitations which had to be overcome. First, there is no public database of U.S. naval installations which contains geospatial and time series data. This data had to be gathered and a new dataset created. The Issue Correlates of War project publishes numerous datasets which contained the majority of the remainder of the information needed. Information on alliance structures and regime type were gathered from the Correlates of War project and Polity IV project respectively. After creating this dataset I test my hypotheses using a logistic regression with four models and report as coefficients rather than log-odds ratios.

Dependent Variable
     The dependent variable for these models is whether a militarized interstate dispute (MID) had occurred between the dyad over that claim in a given year. A MID is a military action ranging from threats to conflict short of war, which is defined as conflict exceeding 1000 battle deaths (Maoz et al. 2018, 7-8) . The Issue Correlates of War project has compiled a dataset of territorial, river, and maritime claims for nearly 200 dyad years. These claims are the argument between two or more actors that they have the right to use or take ownership of a specific maritime space. For example, the contention by China that it has economic rights to the maritime area within their so called Nine-Dash line. This dataset includes indicators on whether the claim resulted in a MID. This paper is particularly interested in maritime claim, and so both territorial and river disputes were dropped from the data. After dropping the two other types of issue claims, there were a total number of 3,226 dyad-years in which a maritime claim had occurred. Looking only at maritime claims, there were 91 dyad-years in which a dispute saw the initiation of a militarized dispute over that claim. The data was reduced further by removing those dyads in which the United States was either the instigator or the target of the dispute. This removed roughly a third of the available dyad years as well as a third of the MIDs. Data limitations associated with the relative capabilities of some states as well as the level of democracy removed an additional 25 dyad-years. We are then left with a total of 2,109 dyad years from which to analyze the relationships. Of 2,109 dyad-years of maritime claims, 67 resulted in the initiation of a MID. 

Independent variables
     The primary independent variable of interest in this study is the proximity of United States naval installation. This variable is measured in terms of miles from the capital city of the state which made the original challenge, thus starting the maritime claim, to the nearest American naval installation. The capital city of the challenger is selected as the second geospatial starting point because it is the revisionist challenger which has initiated the claim by claiming some area which they do not currently possess. This upsets the status quo which the hegemon is attempting to maintain. 
     A list of naval bases is made public by the Commander, Navy Installations Command (CNIC). This list includes all currently active naval installations both inside the United States as well as overseas. Creating this variable required the creation of a data set with the observations for each naval instillation for each year that it was open. The dataset includes an identifier variable for each installation as well as the installations name. The year that the installation opened is recorded as well as the year it closed. If the installation has not closed but is currently still open, then the end year set to 2018. The latitude and longitude of the installation are also recorded as decimal coordinates. In addition to naval ports, naval air stations were included in this dataset. Naval aviation has become a major component of a state’s naval capabilities, evident by the replacement of the battleship by the aircraft carrier as the fleet’s principle capital ship (Julian 1984, 130). After using a statistical package to calculate the distance between the capital cities of the challenger states to the nearest US naval installation, we are left with 2,109 observations for the analysis.

#(Insert summary statistics/frequency table)

To test the other hypotheses and control for other explanations of dispute militarization, eight additional independent variable were added to the models. First among these are the relative capabilities of the two actors in the dispute. Measuring the capabilities of a state has become an entire body of literature unto itself. What do we mean by capabilities? How do we measure them? Which of these material capabilities contributes the most to a state’s power? All of these questions have been presented by researchers, and for each proposed answer there are a dozen counterarguments. Organski (1968) went so far as to claim that it would be easier to list those countries which have power than it would be to operationalize the concept itself. This research utilizes arguable the most widely used measure for material capabilities, the composite index of national capabilities (CINC) produced by the Correlates of War Program. This data takes six measures of national capabilities, total population, urban population, iron and steel production, energy consumption, military personnel, and military expenditures, and aggregates them into a single score (Singer 1987). CINC is not without its flaws, particularly its propensity to inflate scores for countries with high populations e.g. China, India, and Indonesia. CINC scores have also been found to indicate power transitions which do not occur and does not demonstrate transitions which have occurred (Kadera & Sorokin, 2004). Despite these shortcomings, CINC scores continue to be the most widely used measure of national capabilities, in no small part due to the wide time frame it encompasses and ease of use. To get a measure of relative capabilities, I borrow the relative capabilities measure used in Hensel et al’s. (2008) paper. By taking the strongest member of the dyad and divided their CINC score by the combined CINC of the dyad, I am left with a variable measuring the proportion of material capabilities held by the stronger member of the dyad. A relative capabilities measure near 0.5 would represent a nearly equal balance of power while a score closer to 1 would indicate relative preponderance by one member of the dyad (Hensel et al. 2008, 131). 
	Arguably the most pervasive theory in international relations is the concept of the democratic peace. Put simply, dyads in which both states are democratic tend not to fight in military conflicts with one another. Some researchers argue that it stems from the potential political costs a leader may face from their people (Fearon 1994, 557). Others have argued that democratic states are not presented with the opportunity to fight with one another since democratic states commonly have the same foreign policy preferences (Gartzke 1998). To control for joint democracy, I will include a dichotomous variable that identifies if both states are considered democratic. Categorizing the regime of a state will be done using the Polity IV data produced by the Center for Systemic Peace. Again borrowing the coding used by Hensel et al. (2008), any state which is scored as a 6 or greater on its democracy score will be considered a democratic regime. 
	Research has found that conflict behavior and alliance structures tends to be linked (Leeds 2003, 436). In this research I look specifically at whether the target or challenger have an alliance to the United States. To control for a possible alliance with the United States, I used the Formal Alliance data published by the Correlates of War project. Two variables, one identifying an alliance between the challenger and the United States, and another identifying an alliance between the target and the U.S. are included in the models. Four additional variables are included which account for different issues associated the maritime claim itself. The ICOW data includes these variables to identify the different aspects of issue salience of the particular claim. Included in the models are indicators for whether the claim is over a strategic location, over areas with oil or gas resources, other valuable non-oil resources, and fisheries. 
	Two interaction terms are included in the final model. The first is an interaction between the distance to the nearest US naval base and whether the target of the maritime claim has an alliance with the United States. Having an alliance with the United States may provide more incentive to the U.S. to get involved if a militarized dispute were to occur. This in turn may provide incentive for the challenger state to avoid initiating a MID. If the United States had a naval base near the challenger, this may dramatically increase the deterrence effect of an alliance. An interaction for the distance to a base and whether or not the disputed territory is considered a strategic location is also included in the fourth model. As the hegemonic power, the United States is keenly interested in the protection of trade routes and the openness of strategic waterways. Should the claim cover one of these strategic locations the United States will be more sensitive to attempts to change the status quo in that area, and so the distance to the revisionist state, the challenger, may affect the likelihood of the militarization of that dispute. 
	A final variable identifying whether there had been at least one attempt at bilateral negotiations to reach a settlement to the claim in a given year is included into the model. This variable was included to account for the willingness of the two states to find a peaceful solution. If the two states are willing to attempt a bilateral negotiation to solve the issue, it may indicate that they are more interested in seeking a peaceful settlement to the dispute. If this is true then we should see this variable indicate a negative relationship with the chance of the onset of a MID.

#Results
#Insert table 1
The results of all four models are given in Table 1. The first model is a simple bivariate logistic regression meant to observe the effects of installation proximity on MIDs by itself.  In this first model the relationship between distance to the nearest U.S. naval base and MID initialization is not statistically significant (P > 0.804). The coefficient appears to indicate an extremely weak inverse relationship between distance to an American naval installation and the challenger. However, the result is not significant. 
	Model 2 examines the effects of all controls without inclusion of distance to an American naval installation. Areas where a state may gain strategic benefits from the control of the region are more likely to see a militarized dispute develop. The results show a positive and significant (P > 0.012) relationship between whether the claim area is of strategic significance and the likelihood of a claim developing into a dispute control over strategic locations such as the Suez and Panama canals, Straits of Gibraltar, and Straits of Malacca could allow a state to ensure that trade and shipping move freely across the seas. Similarly, control over strategic locations could allow a state to restrict such commerce and transit. The importance of strategic location is also demonstrated with the interaction term of strategic area and distance being positive and significant. If the area under a claim is of strategic value and the distance from the challenger in the claim to a U.S. naval installation increases, the likelihood that a militarized dispute will occur increases. Additionally, the results demonstrate that the presence of oil in the area under claim will increase the likelihood that a MID may be initiated.  
	Also demonstrated in Model 2 is the profound effect which the history of bilateral attempts has on the likelihood of a claim becoming a dispute. However, the result is counter intuitive. If there is at least one attempt at a bilateral settlement to the dispute in a given year, then the likelihood that the claim will become a military dispute will actually increase. The effect is almost as large as the affect that strategic location has on MID likelihood and is significant at the .05 level. This may be the result of a failure of the attempted negotiation to garner any favorable terms, resulting in at least one side determining that a more aggressive strategy could be more profitable. 
	Model 3 isolates the indicators for different forms of issue salience to observe their impact on conflict by themselves. Once again, the presence of oil resources and the classification of the disputed area as a strategic location are found to be statistically significant. However, in this model the presence of migratory fish stock in the claimed area also increases the likelihood of the claim resulting in a militarized dispute. 
	The final model includes the independent variable as well as all controls. Again, we see that strategic location and the presence of oil resources have a statistically significant impact on the onset of MIDs. Most interesting in this model is that the independent variable becomes significant at the 0.05 level. As the distance between the nearest U.S. naval base and the challenger in the maritime claim increases, the likelihood of the claim becoming a militarized dispute increases as well thus supporting my hypothesis. Migratory fish stocks, which had been shown to impact MID likelihood in model 3, are not significant in this model. However, the interaction between distance and strategic importance is significant, as is the effect of at least one settlement attempt. 

#Conclusion
	This paper attempts to further our knowledge of the impact of naval capabilities on maritime claims by focusing on fixed naval installations of a hegemonic power. By examining geospatial data this paper has demonstrated that as the distance between a hegemon’s naval installations and the challenger in maritime claim increases, the chance that a MID may occur rises, albeit very slightly. Issue specific aspects of maritime claims, namely the presence of oil in the disputed territory or the fact the claimed area is considered a strategic location were found to be significant. Area claims which are considered to be in a strategic location tend to increase the likelihood that the dispute will result in a militarized conflict. The relative capabilities of the dyad are not significant in any model, contrary to the findings of other studies (Hensel et al. 2008, 136). The presence of fishing resources or other valuable non-oil resources were also not found to have a significant effect on dispute militarization. However, migrating fishing stocks were found to have an effect in one model. Additionally, if there has been at least one attempt to negotiate a settlement to the claim in a year, then the likelihood of a MID surprisingly increases.
	While the Issue Correlates of War data provides researchers with a plethora of benefits and opportunities, the data on maritime conflict is still incomplete. To date, only two regions of maritime claims have been included in the data. This means that the relationship between installation proximity and dispute militarization may yield wildly different results when additional regions are added to the existing data. There is also the opportunity to expand this research by examining the relationship in a two stage analysis, looking at onset of a maritime claim as well as the onset of a militarized dispute. It may turn out that states self-select themselves into the sample of potential MIDs by being willing to risk the MID to make the initial claim.    

#Need to include bibliography